CAPTeam14/Controllers/giangVienController.cs
using CAPTeam14.Middleware;
using CAPTeam14.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CAPTeam14.Controllers
{
    [LoginVerification]
    public class giangVienController : Controller
    {
        CP24Team14Entities model = new CP24Team14Entities();
        // GET: giangVien

        public ActionResult Index()
        {
            var giangvien = model.nguoiDungs.OrderBy(x => x.tenGV).ToList();
            return View(giangvien);
        }
        public ActionResult Index2()
        {
            var giangvien = model.nguoiDungs.OrderBy(x => x.tenGV).ToList();
            return View(giangvien);
        }

        [HttpGet]

        public JsonResult Details(int? id)
        {
            ViewBag.active = 11;
            model.Configuration.ProxyCreationEnabled = false;
            var giangvien = model.nguoiDungs.FirstOrDefault(x => x.ID == id);
            string ten = giangvien.tenGV;

            string maGV = "";
            if (giangvien.maGV == null )
            {
                maGV = "Không có";
            }
            else
            {
                maGV = giangvien.maGV;
            }
            string loaiGV = "";
            if (giangvien.loaiGV == true)
            {
                loaiGV = "Cơ hữu";
            }
            else
            {
                loaiGV = "Thỉnh giảng";
            }
            string role = "";
            if (giangvien.role == 1)
            {
                role = "Admin";
            }
            else if (giangvien.role == 2)
            {
                role = "Ban chủ nhiệm khoa";
            }
            else if (giangvien.role == 3)
            {
                role = "Bộ môn";
            }
            else if (giangvien.role == 4)
            {
                role = "Giảng viên";
            }
            else if (giangvien.role == null || giangvien.role == 0)
            {
                role = "Chưa kích hoạt";
            }
            string khoa = giangvien.khoa;
            int? sdt = giangvien.sdt;

            string gioiTinh = "";
            if (giangvien.gioiTinh == true)
            {
                gioiTinh = "Nam";
            }
            else
            {
                gioiTinh = "Nữ";
            }

            var abcdefg = new { a = ten, b = maGV, c = loaiGV, d = role, e = khoa, f = sdt, g = gioiTinh };
            return Json(abcdefg, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]

        public ActionResult Edit(int? id, string email)
        {
            ViewBag.active = 11;
            ViewBag.tt = "Edit";
            var cl = model.nguoiDungs.FirstOrDefault(x => x.ID == id);

            return View(cl);
        }

        [HttpPost]

        public ActionResult Edit(int? id, nguoiDung acc)
        {
            ViewBag.active = 11;
            ViewBag.tt = "Edit";
            /* ValidateClass(cl);*/

            try
            {
                if (ModelState.IsValid)
                {
                    var giangvien = model.nguoiDungs.FirstOrDefault(x => x.ID == id);

                    giangvien.tenGV = acc.tenGV;
                    giangvien.maGV = acc.maGV;
                    giangvien.loaiGV = acc.loaiGV;
                    giangvien.role = acc.role;
                    giangvien.khoa = acc.khoa;
                    giangvien.sdt = acc.sdt;
                    giangvien.userID = acc.userID;
                    giangvien.gioiTinh = acc.gioiTinh;

                    if ((int)Session["id1"] == acc.ID)
                    {
                        TempData["phanquyen1"] = 1;
                        return RedirectToAction("Index");
                    }
                    model.SaveChanges();
                    TempData["phanquyen"] = 1;
                    return RedirectToAction("Index");
                }
                else
                {
                    string messages = string.Join("; ", ModelState.Values
                                        .SelectMany(x => x.Errors)
                                        .Select(x => x.ErrorMessage));
                    ModelState.AddModelError("", messages);
                }
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Không thể lưu các thay đổi. Hãy thử lại và nếu sự cố vẫn tiếp diễn, hãy gặp quản trị viên hệ thống của bạn.");
            }

            return View(acc);
        }


        [HttpGet]
        [LoginVerification]
        public ActionResult DetailStatistic(int? id, int? idhk)
        {
            var cl = model.danhsachGVs.FirstOrDefault(x => x.ID == id);
            ViewBag.tengv = cl.tenGV;
            ViewBag.maid = cl.ID;
            //ViewBag.active = 7;
            //ViewBag.year = year;
            //int result = Int32.Parse(year);
            //ViewBag.sumclassweek = model.TKBs.Where(x => x.ID_GV == cl.ID && x.ID_hocKy == idhk).ToList().Count();
            //ViewBag.sumgghk = (decimal)(ViewBag.sumclassweek * 150) / 60;
            //ViewBag.sumsubhk = model.ACCOUNTs.Where(x => x.DATE_OF_REGISTRATION.Value.Year == result).ToList().Count();
            return View(cl);

        }

        [HttpGet]
        public ActionResult thongke(int? idgv, int? idhk, TKB tkb)
        {
            var cl = model.danhsachGVs.FirstOrDefault(x => x.ID == idgv);
            //đếm tổng số lớp trong 1 tuần
            ViewBag.sumclassweek = model.TKBs.Where(x => x.ID_GV == cl.ID && x.ID_hocKy == idhk).ToList().Count();

            // tính tổng giờ dạy trong 1 tuần
            //ViewBag.sumgghk = (decimal)(ViewBag.sumclassweek * 150) / 60;

            // tính tổng giờ dạy trong 1 học kỳ
            var dslg = model.TKBs.Where(x => x.ID_GV == cl.ID && x.ID_hocKy == idhk).ToList(); // tìm ra những lớp giảng trong tuần = tolist()
            foreach (var lopgiang in dslg.Select(x => x.tuanHoc.tuanHoc1)) //dùng foreach + linq để truy xuất ra những tuần dạng string theo lớp giảng
            {

                //ViewBag.sumALL += lopgiang;
                string rs = string.Join(",", dslg.Select(x => x.tuanHoc.tuanHoc1)); // dùng lệnh join để cộng chuỗi tuần lại và ngăn cách bởi dấu phẩy
                var ff = rs.Split(',', ';', ' ').Length; // tách 
                for (int i = 1; i < ff + 1; i++)
                {
                    ViewBag.sumghk = (double)2.5 * i; // đếm 

                }
            }

            // đếm tổng số môn dạy trong 1 học kỳ
            ViewBag.sumsubhk = model.TKBs.Where(x => x.ID_GV == cl.ID && x.ID_hocKy == idhk).Select(x => x.ID_monHoc).Distinct().ToList().Count();
            //var abc = new { a = sumclassweek };
            var resu = new
            {
                tongloptuan = ViewBag.sumclassweek,
                tonggiohk = ViewBag.sumghk,
                tongmonhk = ViewBag.sumsubhk
            };
            return Json(resu, JsonRequestBehavior.AllowGet);

        }


        // DetailStatistic cho giảng viên
        [HttpGet]
        [LoginVerification]
        public ActionResult DetailStatistic1(int? id, int? idhk)
        {

            ViewBag.tengv = Session["hoten"];
            ViewBag.maid = Session["id1"];
            //ViewBag.active = 7;
            //ViewBag.year = year;
            //int result = Int32.Parse(year);
            //ViewBag.sumclassweek = model.TKBs.Where(x => x.ID_GV == cl.ID && x.ID_hocKy == idhk).ToList().Count();
            //ViewBag.sumgghk = (decimal)(ViewBag.sumclassweek * 150) / 60;
            //ViewBag.sumsubhk = model.ACCOUNTs.Where(x => x.DATE_OF_REGISTRATION.Value.Year == result).ToList().Count();
            return View();

        }

        // DetailStatistic cho giảng viên
        [HttpGet]
        public ActionResult thongke1(int? idgv, int? idhk, TKB tkb)
        {

            var id = Convert.ToInt32(Session["id"]);
            //đếm tổng số lớp trong 1 tuần
            ViewBag.sumclassweek = model.TKBs.Where(x => x.ID_GV == id && x.ID_hocKy == idhk).ToList().Count();

            // tính tổng giờ dạy trong 1 học kỳ
            var dslg = model.TKBs.Where(x => x.ID_GV == id && x.ID_hocKy == idhk).ToList(); // tìm ra những lớp giảng trong tuần = tolist()
            foreach (var lopgiang in dslg.Select(x => x.tuanHoc.tuanHoc1)) //dùng foreach + linq để truy xuất ra những tuần dạng string theo lớp giảng
            {

                //ViewBag.sumALL += lopgiang;
                string rs = string.Join(",", dslg.Select(x => x.tuanHoc.tuanHoc1)); // dùng lệnh join để cộng chuỗi tuần lại và ngăn cách bởi dấu phẩy
                var ff = rs.Split(',', ';', ' ').Length; // tách 
                for (int i = 1; i < ff + 1; i++)
                {
                    ViewBag.sumghk = (double)2.5 * i; // đếm 
                    if (ViewBag.sumghk == null)
                    {
                        ViewBag.sumghk = 0;
                    }

                }
            }



            // đếm tổng số môn dạy trong 1 học kỳ
            ViewBag.sumsubhk = model.TKBs.Where(x => x.ID_GV == id && x.ID_hocKy == idhk).Select(x => x.ID_monHoc).Distinct().ToList().Count();
            var resu = new
            {
                tongloptuan = ViewBag.sumclassweek,
                tonggiohk = ViewBag.sumghk,
                tongmonhk = ViewBag.sumsubhk
            };
            return Json(resu, JsonRequestBehavior.AllowGet);

        }


        // DetailStatistic cho giảng viên
        [HttpGet]
        [LoginVerification]
        public ActionResult DetailStatisticAll(int? id)
        {
            //var tkb1 = model.hocKies.FirstOrDefault(x => x.ID == id);
            //TempData["idhk"] = tkb1.ID;
            //ViewBag.tengv = Session["hoten"];
            //ViewBag.maid = Session["id1"];
            //ViewBag.active = 7;
            //ViewBag.year = year;
            //int result = Int32.Parse(year);

CAPTeam14/Views/giangVien/DetailStatistic.cshtml
@using CAPTeam14.Models;
@{
    ViewBag.Title = "DetailStatistic";
    Layout = "~/Views/Shared/_LayoutTemplate.cshtml";

    var db = new CP24Team14Entities();
    List<int> Lsumclassweek = new List<int>();
    List<int> Lsumgghk = new List<int>();
    List<int> Lsumsubhk = new List<int>();
    //List<int> st = new List<int>();
    //List<int> at = new List<int>();
    //List<int> fqt = new List<int>();
    //var qtm = db.QUESTIONs.ToList();
    //int result = Int32.Parse(ViewBag.year);
    for (int i = 1; i <= 12; i++)
    {
        //var item1 = db.QUESTIONs.Where(x => x.DATE.Month == i && x.DATE.Year == result).ToList().Count;
        //var item2 = db.QUESTIONs.Where(x => x.DATE.Month == i && x.DATE.Year == result && x.ANSWER != null).ToList().Count;
        //var item3 = db.QUESTIONs.Where(x => x.DATE.Month == i && x.DATE.Year == result && x.ANSWER == null).ToList().Count;
        //var item4 = db.STUDENTs.Where(x => x.DATE_CREATED.Value.Month == i && x.DATE_CREATED.Value.Year == result).ToList().Count;
        //var item5 = db.ACCOUNTs.Where(x => x.DATE_OF_REGISTRATION.Value.Month == i && x.DATE_OF_REGISTRATION.Value.Year == result).ToList().Count;
        //var item6 = db.FAVORITE_QUESTION.Where(x => x.DATE.Month == i && x.DATE.Year == result).ToList().Count;
        //qt.Add(item1);
        //qnat.Add(item2);
        //qat.Add(item3);
        //st.Add(item4);
        //at.Add(item5);
        //fqt.Add(item6);
    }
}

<div class="content-wrapper text-sm">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2 mt-2">
                <div class="col-12">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index1","Home")">Trang chủ</a></li>
                        <li class="breadcrumb-item active">Thống kê </li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">
                                Dữ liệu thống kê của giảng viên <strong>@ViewBag.tengv</strong> trong
                                <select style="margin-left:5px" id="chonhk">
                                    <option>Chọn học kỳ</option>
                                    @foreach (var itemHK in db.hocKies)
                                    {
                                        <option value="@itemHK.ID">@itemHK.tenHK</option>
                                    }
                                </select>
                            </h3>
                        </div>
                        <div class="card-body">
                            <table class="table table-bordered">
                                <thead>
                                    <tr style="background-color:cornflowerblue">
                                        <th class="text-center">STT</th>
                                        <th class="text-center">Thông tin dữ liệu</th>
                                        <th class="text-center">Số lượng</th>
                                    </tr>
                                </thead>
                                <tbody>

                                    @*<tr>
                                            <td class="text-center">
                                                1
                                            </td>
                                            <td class="text-center">
                                                Số giờ giảng trong học kỳ
                                            </td>
                                            <td class="text-center">
                                                @ViewBag.sumgghk (giờ)
                                            </td>
                                        </tr>

                                        <tr>
                                            <td class="text-center">
                                                2
                                            </td>
                                            <td class="text-center">
                                                Số lớp giảng cao nhất trong tuần
                                            </td>
                                            <td class="text-center">
                                                @ViewBag.sumclassweek
                                            </td>
                                        </tr>

                                        <tr>
                                            <td class="text-center">
                                                3
                                            </td>
                                            <td class="text-center">
                                                Số môn giảng trong học kỳ
                                            </td>
                                            <td class="text-center">
                                                @ViewBag.qna
                                            </td>
                                        </tr>*@

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body" id="graph-container">
                            <canvas id="myChart" class="h-100"></canvas>
                        </div>
                    </div>
                </div>
            </div>

            @*<div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-body">
                                <canvas id="myChartAll" class="h-auto"></canvas>
                            </div>
                        </div>
                    </div>
                </div>*@

            @*<div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-body">
                                <canvas id="myChart6" class="h-50"></canvas>
                            </div>
                        </div>
                    </div>
                </div>*@
        </div>
    </section>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.4.0/chart.min.js" integrity="sha512-JxJpoAvmomz0MbIgw9mx+zZJLEvC6hIgQ6NcpFhVmbK1Uh5WynnRTTSGv3BTZMNBpPbocmdSJfldgV5lVnPtIw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    $('#chonhk').on('change', function () {
        var valur = $(this).val();
        if (valur) {
            $.ajax({
            url: '@Url.Action("thongke", "giangVien")',
            type: 'GET',
            contentType: 'application/json; charset=UTF-8',
            dataType: 'html',
                data: {
                idgv: '@ViewBag.maid',
                idhk: valur
            },
            success: function (r) {
                //$('#idtbody').remove();
                data = JSON.parse(r)
                if (data.tonggiohk == null) {
                    data.tonggiohk = 0;
                }
                $('tbody').html(
                    '<tr>' +
                    '<td class="text-center"> 1 </td>' +
                    '<td class="text-center"> Số giờ giảng trong học kỳ </td>' +
                    '<td td class="text-center">' + data.tonggiohk  + '(giờ) </td>' +
                    '<tr>' +
                    '<td class="text-center"> 2 </td>' +
                    '<td class="text-center"> Số lớp giảng cao nhất trong tuần </td>' +
                    '<td class="text-center">' + data.tongloptuan + '</td>' +
                    '<tr>' +
                    '<td class="text-center"> 3 </td>' +
                    '<td class="text-center"> Số môn giảng trong học kỳ </td>' +
                    '<td class="text-center">' + data.tongmonhk + '</td>'
                )
            },
            error: function (errormessage) {
                Swal.fire({
                    title: 'Thông báo',
                    text: 'Hiện tại đang có lỗi. Vui lòng thử lại !!!',
                    icon: 'error',
                });
            }
            });
        }

    });
</script>

<script type="text/javascript">
    @*var myChart6 = new Chart(
        document.getElementById('myChart6'),
        {
            type: 'line',
            data: {
                labels: [
                    '01',
                    '02',
                    '03',
                    '04',
                    '05',
                    '06',
                    '07',
                    '08',
                    '09',
                    '10',
                    '11',
                    '12',
                ],
                datasets: [{
                    label: 'Số lượng like các câu hỏi',
                    backgroundColor: 'rgba(255, 159, 64, 1)',
                    borderColor: 'rgba(255, 159, 64, 1)',
                    data: [@fqt[0], @fqt[1], @fqt[2], @fqt[3], @fqt[4], @fqt[5], @fqt[6], @fqt[7], @fqt[8], @fqt[9], @fqt[10], @fqt[11]],
                }]
            },
            options: {}
        }
    );*@

</script>

<script>
    $('#chonhk').on('change', function () {

        var valur = $(this).val();
        if (valur) {
            $.ajax({
            url: '@Url.Action("thongke", "giangVien")',
            type: 'GET',
            contentType: 'application/json; charset=UTF-8',
            dataType: 'html',
                data: {
                idgv: '@ViewBag.maid',
                idhk: valur
            },
            success: function (r) {
                data = JSON.parse(r)
                $('#myChart').remove(); // this is my <canvas> element
                $('#graph-container').append('<canvas id="myChart" class="h-100"></canvas>');
                var ctx = document.getElementById('myChart').getContext("2d");
                var myChart = new Chart(ctx, {
                    type: 'bar',
                    data: {
                        labels: [
                            'Số giờ giảng trong học kỳ',
                            'Số lớp giảng cao nhất trong tuần',
                            'Số môn giảng trong học kỳ',      
                        ],
                        datasets: [{
                            label: 'Bảng dữ liệu thống kê',
                            @* data: [@ViewBag.sumclassweek, @ViewBag.sumgghk, @ViewBag.sumsubhk],*@
                            data: [data.tonggiohk, data.tongloptuan, data.tongmonhk],
                            @* data: [@ViewBag.qt, @ViewBag.qa, @ViewBag.qna, @ViewBag.stu, @ViewBag.acc, @ViewBag.fq],*@
                            backgroundColor: [
                                'rgba(255, 99, 132, 0.8)',
                                'rgba(54, 162, 235, 0.8)',
                                'rgba(255, 206, 86, 0.8)',

                            ],
                            borderColor: [
                                'rgba(255, 99, 132, 1)',
                                'rgba(54, 162, 235, 1)',
                                'rgba(255, 206, 86, 1)',
                            ],
                            borderWidth: 4

                        }]
                    },
                    options: {
                        scales: {
                            y: {
                                beginAtZero: true,
                            }
                        }
                    }
                });
                myChart.render();
            }
            });
        }
    });
</script>

CAPTeam14/Views/giangVien/Edit.cshtml
@model CAPTeam14.Models.nguoiDung

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutTemplate.cshtml";
}





@using (Html.BeginForm())
{





    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">

                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                             <li class="breadcrumb-item"><a href="@Url.Action("Index1","Home")">Trang chủ</a></li>
                            <li class="breadcrumb-item active">Phân Quyền</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row d-flex justify-content-center">
                    <div class="col-md-5">
                        <div class="card">
                            <form role="form">
                                @Html.AntiForgeryToken()

                                <div class="card-body">

                                    <hr />
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                    @Html.HiddenFor(model => model.ID)
                                    @Html.HiddenFor(model => model.gioiTinh)
                                    @Html.HiddenFor(model => model.khoa)
                                    @Html.HiddenFor(model => model.loaiGV)
                                    @Html.HiddenFor(model => model.sdt)
                                    @Html.HiddenFor(model => model.userID)



                                    <div class="form-group">
                                        <label>Mã giảng viên</label>
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text"><i class="far fa-envelope"></i></span>
                                            </div>

                                            @Html.EditorFor(model => model.maGV, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                            @Html.ValidationMessageFor(model => model.maGV, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label>Họ tên</label>
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text"><i class="far fa-user"></i></span>
                                            </div>
                                            @Html.EditorFor(model => model.tenGV, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                            @Html.ValidationMessageFor(model => model.tenGV, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label>Loại giảng viên</label>
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text"><i class="far fa-envelope"></i></span>
                                            </div>
                                            @if (Model.loaiGV == true)
                                            {
                                                <input type="text" class="form-control" readonly="readonly" value="Cơ Hữu">
                                            }
                                            else
                                            {
                                                <input type="text" class="form-control" readonly="readonly" value="Thỉnh Giảng">
                                            }
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label>Giới tính</label>
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text"><i class="far fa-envelope"></i></span>
                                            </div>
                                            @if (Model.gioiTinh == true)
                                            {
                                                <input type="text" class="form-control" readonly="readonly" value="Nam">
                                            }
                                            else
                                            {
                                                <input type="text" class="form-control" readonly="readonly" value="Nữ">
                                            }
                                        </div>
                                    </div>





                                    <div class="form-group">
                                        <label>Vai trò</label>
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text"><i class="fa fa-tasks"></i></span>
                                            </div>
                                            @{
                                                List<SelectListItem> listItems = new List<SelectListItem>();

                                                listItems.Add(new SelectListItem
                                                {
                                                    Text = "Chưa kích hoạt",
                                                    Value = "0",
                                                });

                                                listItems.Add(new SelectListItem
                                                {
                                                    Text = "Admin",
                                                    Value = "1",
                                                });
                                                listItems.Add(new SelectListItem
                                                {
                                                    Text = "Ban chủ nhiệm khoa",
                                                    Value = "2"
                                                });
                                                listItems.Add(new SelectListItem
                                                {
                                                    Text = "Bộ môn",
                                                    Value = "3"
                                                });
                                                listItems.Add(new SelectListItem
                                                {
                                                    Text = "Giảng viên",
                                                    Value = "4"
                                                });
                                            }
                                            @Html.DropDownListFor(model => model.role, listItems, new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.role, "", new { @class = "text-danger" })
                                        </div>
                                    </div>





                                    <div class="row">
                                        <div class="col-6">
                                            <a class="btn btn-danger btn-block" href="@Url.Action("Index", "giangVien")">Quay lại</a>
                                        </div>
                                        <div class="col-6">
                                            <button type="submit" value="Save" class="btn btn-success btn-block">Phân Quyền</button>
                                        </div>
                                    </div>
                                </div>
                            </form>






                        </div>
                    </div>
                </div>
            </div>

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")



}